#!/usr/bin/env bash
# ClaudeMix — merge-queue.sh
# Consolidate multiple session branches into a single PR.
# Reduces CI churn when many Claude sessions work in parallel.
# Sourced by other modules. Never executed directly.

# ── Merge Queue Operations ───────────────────────────────────────────────────

# Interactive merge queue: select branches, consolidate, create PR.
merge_queue_run() {
  require_project
  load_config

  if ! has_cmd gh; then
    die "GitHub CLI (gh) is required for merge queue. Install with: brew install gh"
  fi

  # Get all claudemix branches that have been pushed
  local branches=()
  while IFS= read -r branch; do
    [[ -z "$branch" ]] && continue
    # Check if branch has commits ahead of merge target
    local ahead
    ahead=$(git -C "$PROJECT_ROOT" rev-list --count "$CFG_MERGE_TARGET..$branch" 2>/dev/null || echo "0")
    if (( ahead > 0 )); then
      branches+=("$branch ($ahead commits)")
    fi
  done < <(git -C "$PROJECT_ROOT" branch --list "${CLAUDEMIX_BRANCH_PREFIX}*" 2>/dev/null | sed 's/^[* ]*//')

  if (( ${#branches[@]} == 0 )); then
    log_info "No branches ready to merge."
    return 0
  fi

  # Select branches to consolidate
  local selected=()
  if gum_available; then
    log_info "Select branches to consolidate into a single PR:"
    local choices
    choices="$(printf '%s\n' "${branches[@]}" | gum choose --no-limit --header "Select branches (space to toggle, enter to confirm)")" || return 0
    while IFS= read -r choice; do
      [[ -z "$choice" ]] && continue
      # Extract branch name (remove commit count)
      selected+=("$(echo "$choice" | sed 's/ (.*//')")
    done <<< "$choices"
  else
    echo ""
    echo "Available branches:"
    local i=1
    for branch in "${branches[@]}"; do
      echo "  $i) $branch"
      ((i++))
    done
    echo ""
    echo -n "Enter branch numbers to merge (comma-separated, e.g., 1,3,5): "
    read -r selections
    IFS=',' read -ra nums <<< "$selections"
    for num in "${nums[@]}"; do
      num="$(echo "$num" | tr -d '[:space:]')"
      if [[ "$num" =~ ^[0-9]+$ ]] && (( num >= 1 && num <= ${#branches[@]} )); then
        local branch_entry="${branches[$((num-1))]}"
        selected+=("$(echo "$branch_entry" | sed 's/ (.*//')")
      fi
    done
  fi

  if (( ${#selected[@]} == 0 )); then
    log_info "No branches selected."
    return 0
  fi

  log_info "Selected ${#selected[@]} branch(es) for consolidation"

  # Create consolidated branch
  local timestamp
  timestamp="$(date '+%Y%m%d-%H%M%S')"
  local merge_branch="claudemix/merge-${timestamp}"

  log_info "Creating consolidated branch ${CYAN}$merge_branch${RESET} from ${CYAN}$CFG_MERGE_TARGET${RESET}"

  git -C "$PROJECT_ROOT" checkout "$CFG_MERGE_TARGET" --quiet 2>/dev/null
  git -C "$PROJECT_ROOT" pull origin "$CFG_MERGE_TARGET" --quiet 2>/dev/null || true
  git -C "$PROJECT_ROOT" checkout -b "$merge_branch" --quiet 2>/dev/null || {
    die "Failed to create merge branch"
  }

  # Merge each selected branch
  local merged=0
  local failed=()
  for branch in "${selected[@]}"; do
    log_info "Merging ${CYAN}$branch${RESET}..."
    if git -C "$PROJECT_ROOT" merge "$branch" --no-edit --quiet 2>/dev/null; then
      ((merged++))
      log_ok "Merged $branch"
    else
      log_error "Conflict merging $branch — aborting this merge"
      git -C "$PROJECT_ROOT" merge --abort 2>/dev/null || true
      failed+=("$branch")
    fi
  done

  if (( merged == 0 )); then
    log_error "No branches could be merged. Cleaning up."
    git -C "$PROJECT_ROOT" checkout "$CFG_MERGE_TARGET" --quiet 2>/dev/null
    git -C "$PROJECT_ROOT" branch -D "$merge_branch" 2>/dev/null || true
    return 1
  fi

  # Run validation on consolidated result
  if [[ -n "$CFG_VALIDATE" ]]; then
    log_info "Running validation on consolidated branch..."
    if ! (cd "$PROJECT_ROOT" && eval "$CFG_VALIDATE"); then
      log_error "Validation failed on consolidated branch."
      log_warn "Fix issues and run: git push -u origin $merge_branch && gh pr create"
      return 1
    fi
    log_ok "Validation passed"
  fi

  # Push and create PR
  log_info "Pushing ${CYAN}$merge_branch${RESET}..."
  git -C "$PROJECT_ROOT" push -u origin "$merge_branch" 2>/dev/null || {
    die "Failed to push branch"
  }

  # Build PR body
  local pr_body="## Consolidated PR\n\n"
  pr_body+="Merges ${merged} branch(es) from ClaudeMix sessions:\n\n"
  for branch in "${selected[@]}"; do
    local is_failed=false
    for f in "${failed[@]}"; do
      [[ "$f" == "$branch" ]] && is_failed=true && break
    done
    if $is_failed; then
      pr_body+="- ❌ \`$branch\` (conflict — skipped)\n"
    else
      pr_body+="- ✅ \`$branch\`\n"
    fi
  done

  if (( ${#failed[@]} > 0 )); then
    pr_body+="\n### Skipped (conflicts)\n\n"
    pr_body+="These branches had conflicts and need manual resolution:\n\n"
    for branch in "${failed[@]}"; do
      pr_body+="- \`$branch\`\n"
    done
  fi

  pr_body+="\n---\n*Generated by [ClaudeMix](https://github.com/Draidel/ClaudeMix)*"

  local pr_title="chore: consolidate ${merged} ClaudeMix session(s)"

  log_info "Creating PR..."
  local pr_url
  pr_url="$(gh pr create \
    --repo "$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null)" \
    --base "$CFG_MERGE_TARGET" \
    --head "$merge_branch" \
    --title "$pr_title" \
    --body "$(echo -e "$pr_body")" \
    2>/dev/null)" || {
    die "Failed to create PR. Push succeeded — create manually: gh pr create"
  }

  log_ok "PR created: $pr_url"

  # Enable auto-merge if squash strategy
  if [[ "$CFG_MERGE_STRATEGY" == "squash" ]]; then
    gh pr merge --auto --squash "$pr_url" 2>/dev/null || true
    log_ok "Auto-merge enabled (squash)"
  fi

  # Return to original branch
  git -C "$PROJECT_ROOT" checkout "$CFG_MERGE_TARGET" --quiet 2>/dev/null || true

  echo ""
  log_ok "Consolidated ${GREEN}$merged${RESET} branches into ${CYAN}$pr_url${RESET}"
  if (( ${#failed[@]} > 0 )); then
    log_warn "${#failed[@]} branch(es) skipped due to conflicts"
  fi
}

# List branches eligible for merge queue.
merge_queue_list() {
  require_project
  load_config

  local branches
  branches="$(git -C "$PROJECT_ROOT" branch --list "${CLAUDEMIX_BRANCH_PREFIX}*" 2>/dev/null | sed 's/^[* ]*//')"

  if [[ -z "$branches" ]]; then
    log_info "No ClaudeMix branches found."
    return 0
  fi

  printf "${BOLD}%-35s %-8s %-8s %s${RESET}\n" "BRANCH" "AHEAD" "BEHIND" "STATUS"
  printf "%-35s %-8s %-8s %s\n" "──────" "─────" "──────" "──────"

  while IFS= read -r branch; do
    [[ -z "$branch" ]] && continue
    local ahead behind status
    ahead=$(git -C "$PROJECT_ROOT" rev-list --count "$CFG_MERGE_TARGET..$branch" 2>/dev/null || echo "?")
    behind=$(git -C "$PROJECT_ROOT" rev-list --count "$branch..$CFG_MERGE_TARGET" 2>/dev/null || echo "?")

    if [[ "$ahead" == "0" ]]; then
      status="${DIM}merged${RESET}"
    elif [[ "$behind" != "0" ]]; then
      status="${YELLOW}needs rebase${RESET}"
    else
      status="${GREEN}ready${RESET}"
    fi

    printf "%-35s %-8s %-8s %b\n" "$branch" "+$ahead" "-$behind" "$status"
  done <<< "$branches"
}
